# Generated by Django 5.2.1 on 2025-05-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_clustergenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustergenero',
            name='fecha_y_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
