# Generated by Django 5.2.1 on 2025-05-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_clustergenero_fecha_y_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clustergenero',
            old_name='llave',
            new_name='cluster_id',
        ),
        migrations.RenameField(
            model_name='clustergenero',
            old_name='fecha_y_hora',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='clustergenero',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clustergenero',
            old_name='identificador',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='clustergenero',
            old_name='nombre',
            new_name='name',
        ),
    ]
