name: Ejecutar Pruebas Unitarias

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r API/requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar pruebas con cobertura
        run: |
          pytest API/Test --cov=API --cov-report=term-missing --cov-report=html

      - name: Subir reporte HTML de cobertura como artefacto
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reporte-cobertura
          path: htmlcov/
