name: Ejecutar Pruebas Unitarias

on:
  pull_request:
    branches: '**' # Ramas donde quieres aplicar la regla

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r API/requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar pruebas con cobertura
        run: |
          cd API
          PYTHONPATH=. pytest Test --cov=API --cov-report=html

      - name: Publicar reporte de cobertura (opcional)
        if: always()
        run: echo "Revisión manual en la terminal o HTML"

